# This query searches for pokemon having a german name like "Ento.*"
# Should return Psyduck and Golduck

query searchForPokemonInGerman {
  pokemon_v3_pokemonspecies(
    where: {
      pokemon_v3_pokemonspeciesnames: {
        pokemon_v3_language: { name: { _eq: "de" } }
        name: { _regex: "Ento.*" }
      }
    }
  ) {
    pokemon_v3_pokemonspeciesnames(
      where: { pokemon_v3_language: { name: { _eq: "de" } } }
    ) {
      name
    }
    id
  }
}
